name: Deployment

on:
  workflow_run:
    workflows: [Docker Image CI]
    types: [completed]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:        
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY }}
        ssh-known-hosts: ${{ secrets.SERVER_IP }}
      
    - name: connect and pull
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          cd example-voting-app && \
          docker-compose pull && \
          docker-compose up -d
          "


